# Generated by Django 5.2.7 on 2025-11-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
