# Generated by Django 5.2.7 on 2025-11-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_rename_genres_title_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
