# Generated by Django 5.2.7 on 2025-11-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_review_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitleReviews',
        ),
    ]
