# Generated by Django 5.2.7 on 2025-11-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_delete_titlereviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='reviews',
            new_name='review',
        ),
    ]
