# Generated by Django 5.2.7 on 2025-11-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
